title: nicegong的博客
email: zjsgyb@gmail.com
description: >- # 网站的描述
  这是nicegong的个人博客
keywords: 前端开发 nicegong 前端 zjgyb gyb lxgyb zjsgyb # 关键词
author: zjgyb, nicegong, zjsgyb@gmail.com # 作者
linkIco: "photoes/ico.jpg" # 网站图标
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zjgyb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
article-img: "photoes/default.jpg" # 图片路径
twitter_username: lxgyb
github_username:  zjgyb

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
    sass-dir: _sass
    style: compressed

paginate: 6 # 文章数
paginate_path: "page:num"

excerpt_separator: '<!-- more -->' # 摘要
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
